version: '3'
services:
  registry-service:
    image: microservice-docker-registry-service:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
  config-service:
    image: microservice-docker-config-service:0.0.1-SNAPSHOT
    links:
      - registry-service
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://registry-service:8761/eureka
    depends_on:
      - registry-service
    ports:
      - 8888:8888
  technical-service:
    image: microservice-docker-technical-service:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://registry-service:8761/eureka
    restart: on-failure
    depends_on:
      - registry-service
      - config-service
    ports:
      - 8081:8081
  gateway-service:
    image: microservice-docker-gateway-service:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://registry-service:8761/eureka
    ports:
      - 8080:8080
    depends_on:
      - config-service
      - registry-service
      - technical-service



